### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by mr-mmmmore** [sligodave/sublime_remote_edit#10]
Whatever I try to do gives me this error in the console :

```Traceback (most recent call last):
File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
File "remote_edit in /Users/xxxxx/Library/Application Support/Sublime Text 3/Installed Packages/RemoteEdit.sublime-package", line 136, in run
File "remote_edit in /Users/xxxxx/Library/Application Support/Sublime Text 3/Installed Packages/RemoteEdit.sublime-package", line 34, in get_settings
AttributeError: 'NoneType' object has no attribute 'get'
```

I don't know Python but i'm wondering if that doesn't mean that the loading of the settings fails.

I installed with Package Control, then created the file RemoteEdit.sublime-settings in Packages/User/ (it was not there yet) and copy/paste the config example given.

My config file now looks like this :

```
{
    "debug": true,
    "ssh_configs": {
        "myconfigname": {
            // Address of the remote server
            // Not required, will default to the "ALIAS_NAME" string
            "address": "my.server.com",
            // Username to log into server with
            // Not required, the command line scp will default it to current user
            "username": "myuser",
            // NOTE: Remember, to authenticate you need to have your pub key
            // registered in the remote server ssh's authorized_keys file.,
            "create_if_missing": false

        }
    }
}
```

I get the above error when I use the "Open Remote File Prompt" command, or if I try to use the command line with `subl --command 'remote_edit_open_remote_file {"alias": "'my.server.com", "path": ""}'`

I find it weird that the config file doesn't appear in the Preferences > Package Settings menu.

Any idea? I would love to use this package!

**Comment by Aqru** [comment]
All of you need - create a Project.
For some reason plugin try to get project settings even if project not exist at all.

**Comment by mr-mmmmore** [comment]
OK I'll try that and let you know.

Thanks!

**Comment by mr-mmmmore** [comment]
I confirm that if I first open a folder in sublime text, then the package works and I can browse the remote server and edit remote files! Yoohoo! Thanks!
